class TrendInterface:
    data:dict

    def findAllEma():
        ...
    def findAllTrend():
        ...
    def isSideways():
        ...
    def isUptrend():
        ...
    def getTrend():
        ...